### ISSUE TITLE
summarizer appears to require a complete project

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#19]
if only 1 sample is run I get: 

```
Error loading real counts file: /sfs/lustre/allocations/shefflab/processed/ppqc/results_pipeline/GSM1558746/QC_hg38/GSM1558746_preseq_counts.txt
File could not be found.
```

summary output figure is not produced. instead of dying if one sample is missing, it just just produce an incomplete summary.

**Comment by nsheff** [comment]
```
code/peppro/tools/PEPPRO_summarizer.R code/ppqc/ppqc_config.yaml
```

**Comment by jpsmith5** [comment]
I believe this has already been solved.  If it reappears can return to this issue. Closing for now.
