### ISSUE TITLE
Update refgenie docs

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#2]
New system will be much simpler. include a link to:

http://refgenie.databio.org/en/dev/install/

and this guide:

```
# Install refgenie: 
pip install --user refgenie
# Initialize a folder for genome indexes and config file
export REFGENIE=genome_folder/genome_config.yaml
refgenie init $REFGENIE
# Pull necessary assets
refgenie pull -g hg38 -a bowtie2_index
refgenie pull -g rCRSD -a bowtie2_index
...
```

**Comment by jpsmith5** [comment]
Updated docs and using new system in current release [0.7.1]

**Comment by nsheff** [comment]
are you sure about section 4 on the GENOMES variable? Shouldn't that change to refgenie?
