### ISSUE TITLE
_process_fastq can return 1 or 2 things

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#24]
it's confusing that this function sometimes returns 1 and sometimes 2 things:

https://github.com/databio/peppro/blob/31224c5e7530bbe76079974af661418e70791604/pipelines/peppro.py#L1002-L1025

I think these should either be different functions, or should return 'none' or something. This is not really a sustainable function interface, in my opinion.

**Comment by jpsmith5** [comment]
You're 100% correct.  This all started as part of the primary pipeline before more and more options and caveats had me move it over to one *too* large function.  It could use a break up into multiple smaller functions for each step I think with the individual commands returned potentially before putting them all together.

**Comment by jpsmith5** [comment]
Reworked this procedure whole-sale.
