### ISSUE TITLE
Installing PEPPRO on Rivanna

### ISSUE THREAD

**Issue by ccrobertson** [databio/peppro#3]
Hi Jason,
I'm working on setting up PEPPRO to run on Rivanna. I have a few logistics questions

1. Assemblies: Is the environmental variable $REFGENIE in the PEPPRO documentation equivalent to $GENOMES in the PEPATAC documentation? Wondering because I don't see a "genome_config.yaml" file in the reference genome directories I was pointing to previously (which are maintained by you/Nathan I think)

2. Required software: I'm guessing most/all are already installed on Rivanna/CPHG systems. I dug around a bit and found "modulefiles" for some of the required tools on the t1 drive. 
Couldn't find modulefiles for seqkit, fastp, preseq, wigToBigWig, or bigWigCat. Do I need to install these myself or are there existing installations I can use?

Thanks for the help!

Cassie

**Comment by jpsmith5** [comment]
2. First. Yeah those are all tools you’d need to install yourself. Preseq can be tricky so if you hit errors let me know.

1. Refgenie has undergone some major renovations so it is a new system. Check out the refgenie docs and then next Monday I can also meet in person to go over stuff, but Ill be working from home over next couple days.

Are you running PE samples? If so I need to push some changes to the repo and youll need to update.



________________________________

**Comment by nsheff** [comment]
Cassie, the refgenie docs are now here: [refgenie.databio.org](http://refgenie.databio.org) -- we're shortly going to move PEPATAC to this system as well. it's much easier. But we're in a transition stage...

Jason are you planning on building a singularity container like you did with pepatac?

**Comment by nsheff** [comment]
our new genomes folder is: 

echo $REFGENIE
/project/shefflab/genomes/genomes.yaml

**Comment by ccrobertson** [comment]
Ok great. Thanks to both for the info!

Yes, they are paired end. Jason, I'll read about refgenie now and would be great to chat on Monday afternoon if you're free.

I see now that there's actually already a section on running with a container in the documentation. Sorry, I didn't notice that before.

**Comment by jpsmith5** [comment]
Monday works for me.  Just pushed changes necessary for PE data.  And yes, container should be good to go.

**Comment by nsheff** [comment]
do you have a singularity version built? Or are you going to wait for a "real" release?

**Comment by nsheff** [comment]
The docs link points to: http://big.databio.org/simages/peppro but this is a 404 error.
