### ISSUE TITLE
Rename 'adapter' argument? 

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#33]
The 'adapter' argument is also confusing. I would expect it to be an adapter, but actually it's software:

```
    parser.add_argument("--adapter", dest="adapter",
                        default="fastp", choices=ADAPTER_REMOVAL,
                        help="Name of adapter removal program")
```

Is there a way to specify an adapter? If so, shouldn't this be called 'adapter'? Should this be changed to `adapter-remover`?

Taking a step back:  I'm still strugging to understand the difference between adapter removal and trimming. I think of those as the same thing... Is removing adapters really different from trimming? Why wouldn't this just be 1 option?

**Comment by mjg54** [comment]
trimming is ambiguous. There is a distinction from adapter removal (originally called clipping) and simply shortening a read (originally called trimming). Some programs do both or refer to adapter removal as adapter trimming.
