### ISSUE TITLE
What does 'coverage' do?

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#35]
```
    parser.add_argument("--coverage", action='store_true', default=False,
                        dest="coverage",
                        help="Report library complexity using coverage: "
                             "reads / (bases in genome / read length)")
```

Is there a reason you would want to turn this off? Is it just for computing efficiency? In that case,  would it make sense to combine this into a 'fast mode' with `complexity` (#32) or do they really warrant separate options?

**Comment by jpsmith5** [comment]
This is a user preference output option for preseq plotting, where you can either report complexity as a coverage value or raw numbers. Default is raw numbers. So, purely by preference, not a speed trade-off in this case.

**Comment by nsheff** [comment]
can you rename the argument to be more descriptive of what it does?
