### ISSUE TITLE
chrom_sizes is not an asset

### ISSUE THREAD

**Issue by eugeneke-bioinf** [databio/peppro#46]
I've been trying to get the tutorial listed on peppro's page up and running. I'm stuck on the following error:

> Traceback (most recent call last):
>   File "/home/eke/.local/lib/python3.7/site-packages/attmap/ordattmap.py", line 45, in __getitem__
>     return super(OrdAttMap, self).__getitem__(item)
> KeyError: 'chrom_sizes'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/eke/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 1095, in _assert_gat_exists
>     asset_data = genome[CFG_ASSETS_KEY][aname]
>   File "/home/eke/.local/lib/python3.7/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
>     v = super(PathExAttMap, self).__getitem__(item)
>   File "/home/eke/.local/lib/python3.7/site-packages/attmap/ordattmap.py", line 47, in __getitem__
>     return AttMap.__getitem__(self, item)
>   File "/home/eke/.local/lib/python3.7/site-packages/attmap/attmap.py", line 32, in __getitem__
>     return self.__dict__[item]
> KeyError: 'chrom_sizes'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/NGS/peppro/pipelines/peppro.py", line 2944, in <module>
>     sys.exit(main())
>   File "/home/NGS/peppro/pipelines/peppro.py", line 1528, in main
>     res = _add_resources(args, res)
>   File "/home/NGS/peppro/pipelines/peppro.py", line 1366, in _add_resources
>     res[asset] = rgc.get_asset(args.genome_assembly, asset)
>   File "/home/eke/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 251, in get_asset
>     path = _genome_asset_path(self[CFG_GENOMES_KEY], genome_name, asset_name, tag_name, seek_key, enclosing_dir)
>   File "/home/eke/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 1050, in _genome_asset_path
>     _assert_gat_exists(genomes, gname, aname, tname)
>   File "/home/eke/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 1097, in _assert_gat_exists
>     raise MissingAssetError("Genome '{}' exists, but asset '{}' is missing".format(gname, aname))
> refgenconf.exceptions.MissingAssetError: Genome 'hg38' exists, but asset 'chrom_sizes' is missing
> 
> ### Pipeline failed at:  (01-16 16:14:26) elapsed: 0.0 _TIME_
> 
> Total time: 0:00:00
> Failure reason: Pipeline failure. See details above.
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/eke/.local/lib/python3.7/site-packages/pypiper/manager.py", line 1799, in _exit_handler
>     self.fail_pipeline(Exception("Pipeline failure. See details above."))
>   File "/home/eke/.local/lib/python3.7/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
>     raise exc
> Exception: Pipeline failure. See details above.

When I run refgenie list I have my local assets as:

> hg38/   bowtie2_index:default, fasta.chrom_sizes:default, fasta.fai:default, fasta:default

>

**Comment by nsheff** [comment]
can you confirm what version of refgenie you're using? `refgenie --version`. things have been a little bit in flux as we try to finalize things and the config format changed at some point awhile ago

**Comment by michalstolarczyk** [comment]
Looking at the error messages, the problem here might be a misuse of `refgenconf.get_asset()`

https://github.com/databio/peppro/blob/2e57c0a21908adea27195d20d77fa265eb48b7e3/pipelines/peppro.py#L1365-L1366

`chrom_sizes` is a seek_key within the `fasta` asset, so that's why

> refgenconf.exceptions.MissingAssetError: Genome 'hg38' exists, but asset 'chrom_sizes' is missing

is raised

I think this is fixed on dev branch. @eugeneke-bioinf can you give it a try?

**Comment by nsheff** [comment]
yeah, the current master version must work with a previous version of refgenie (before we restructured the seek keys).

@jpsmith5 I think it's time to do a release of peppro since the current master version is not functional...

**Comment by eugeneke-bioinf** [comment]
Changing to development branch fixed refgenie keys issues. Had to install FLASH, which was no big deal. Just something to note when you update documentation. It's also not recognizing optional annotations but that is likely something on my end.
