### ISSUE TITLE
pigz not found

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#55]
Running on singularity on rivanna here's an error I get:

```
> `flash -q -t 8 --compress-prog=pigz --suffix=gz /project/shefflab/processed/x.fastq.paired.fq /project/shefflab/processed/d/results_pipeline/y.fastq.paired.fq -o ... -d /project/shefflab/processed/d/results_pipeline/...cutadapt` (10392)
<pre>
sh: pigz: not found
sh: pigz: not found
sh: pigz: not found
</pre>
Command completed. Elapsed time: 0:00:00. Running peak memory: 3.599GB.  
  PID: 10392;   Command: flash; Return code: 141;       Memory used: 0.001GB
```

@jpsmith5 did this work for you? Are you not using singularity/rivanna? If the flash command is trying to run pigz but doesn't have it within the container, how can this work? I think the problem is it can't use the pigz container separately, so if flash is using pigz it would need it inside the container...

**Comment by nsheff** [comment]
I believe the solution is: the biocontainer people need to include pigz within the flash container. I would suggest pinging them about this; we've had to do this in the past for other tools that had missing dependencies in the containers.

In the meantime, you can create your own container that has both pigz and flash installed, if you want to use it like this, and put that in the bulker manifest.

Also, if you haven't already, it would be good to run the pipeline through a complete test like this , from scratch, to make sure everything works before we release it.

**Comment by jpsmith5** [comment]
I primarily run it using local installs, so had not been testing extensively with bulker.  Will create that container and add it to the manifest then.

**Comment by jpsmith5** [comment]
May also be able to edit that command in the pipeline itself.  Can confirm pigz is callable first and if not default to gzip.

**Comment by jpsmith5** [comment]
Hmm. I already was checking if pigz was callable.  Guess that means I'll have to make the container either way if it still failed.

**Comment by nsheff** [comment]
Right -- pigz *is* callable because it's in the manifest. But this is a pigz being called from flash, so within another container. It's confusing I know...

**Comment by jpsmith5** [comment]
Yeah, I follow now.  Will make a new flash + pigz container tomorrow as soon as I can and update it.

**Comment by nsheff** [comment]
In other words, a command running in one container is *not* capable of executing a separate command in a container. It causes these kind of errors that can be kind of confusing.

**Comment by nsheff** [comment]
> Will make a new flash + pigz container tomorrow 

sounds good. in the long run, this would be better to fix upstream (in the biocontainer), since anyone using this will not able able to use pigz with flash, so it's a partially broken image.

**Comment by jpsmith5** [comment]
Okay. When you have a chance today can you confirm the updated manifest using the new container is working in your hands?  I updated both the repo and bulker hub manifests.

**Comment by nsheff** [comment]
Thanks, I'm giving it a try now

**Comment by nsheff** [comment]
appears to be working now. thanks!

for now it will work but did you report this upstream? if not, make sure you do -- in the long run, we don't want to maintain our own container if we can help it.
