### ISSUE TITLE
Problem with link text to fastqc reports

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#57]
look here:

http://big.databio.org/papers/peppro/reports/h9_pro-seq_1.html

There are two problems with links to fastqc results for paired end reads: 

1. both fastq reports are linked as "R1"
2. one links to a report for "read 1 processed" and the other leads to "read 2 trimmed" -- are these on trimmed reads or raw reads? or is one done one way and the other done the other way?

**Comment by jpsmith5** [comment]
Update working now to report in looper correctly.
