### ISSUE TITLE
Please consider adding Python versions to requirements.txt

### ISSUE THREAD

**Issue by eugeneke-bioinf** [databio/peppro#59]
I had a bit of trouble installing peppro using the requirements.txt. The root of the issue is that several packages are Python2 only and others are Python3 only.

I've had success doing an automated installation by adding python versions to requirements.txt and then doing both pip and pip3 commands. 

cutadapt;python_version >= '3.0'
loopercli;python_version < '3.0'
numpy;python_version >= '3.0'
pandas;python_version >= '3.0'
logmuse;python_version>= '3.0'
pararead;python_version >= '3.0'
pararead;python_version < '3.0'
pysam;python_version < '3.0'
piper;python_version < '3.0'
refgenconf;python_version < '3.0'
refgenie;python_version < '3.0'

**Comment by nsheff** [comment]
I'm not sure I follow. Why exactly doesn't everyone work on python3? As far as I know all of these packages should work on python 3...

**Comment by eugeneke-bioinf** [comment]
Last week, I installed using pip3 and received errors for pypiper, regconf, pysam, logmuse, and pararead using requirements.txt. I remember aliasing python to python3 and still having issues but I can double check that tomorrow.

**Comment by eugeneke-bioinf** [comment]
After thinking about this more, there is probably no need to invest anymore time in this as its going to be an issue specific to Linux users who are not using conda. As python2 has hit EOL, eventually python will refer to python3 in most distros.

**Comment by nsheff** [comment]
I think I see. I think the problems you ran into are specific to your particular python setup. anyway, thanks.
