### ISSUE TITLE
Peppro cannot find bowtie2 index

### ISSUE THREAD

**Issue by wongwic** [databio/peppro#62]
I was just trying to run peppro on the sample files, but it indicates that the required asset bowtie2_index does not exist. I checked the genome folder and the index does appear to be there. Could you help me understand what's wrong?

Command I am using:

python3.6 ./pipelines/peppro.py   --sample-name test   --genome hg38   --input examples/data/test_r1.fq.gz --adapter-tool cutadapt   --single-or-paired single   -O $HOME/peppro_example/

![image](https://user-images.githubusercontent.com/50065480/77540915-4de2dc00-6e7a-11ea-98a5-a9a9b539328c.png)

![image](https://user-images.githubusercontent.com/50065480/77541021-75d23f80-6e7a-11ea-8c7c-14a881b0ba1e.png)

**Comment by nsheff** [comment]
If you type `refgenie seek hg38/bowtie2_index` what do you see?

**Comment by nsheff** [comment]
@stolarczyk could this be a symptom of the recent refgenconf release?

**Comment by stolarczyk** [comment]
It might be, but it's hard to say since the error we see is the result of exception handling in peppro. It does not come from `refgenconf`

**Comment by nsheff** [comment]
@jpsmith5 do we require this: https://github.com/databio/peppro/pull/63

**Comment by stolarczyk** [comment]
looking at the peppro@master, it still uses `RefGenConf.get_asset()`, which in this particular case is invalid (assets ending with `{genome} do not exist). `RefGenConf.seek()` is the new standard.
See the demonstration:

```
In [1]: from refgenconf import RefGenConf as RGC                                                                                                                                                          

In [2]: rgc = RGC("/Users/mstolarczyk/Desktop/testing/r/g.yaml")                                                                                                                                          

In [3]: rgc.list()                                                                                                                                                                                        
Out[3]: 
OrderedDict([('hg38', ['blacklist']),
             ('mouse_chrM2x', ['bowtie2_index', 'fasta']),
             ('rCRSd',
              ['bismark_bt1_index', 'bowtie2_index', 'bwa_index', 'fasta'])])

In [4]: rgc.get_asset("mouse_chrM2x","bowtie2_index")                                                                                                                                                     
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-e85eba650304> in <module>
----> 1 rgc.get_asset("mouse_chrM2x","bowtie2_index")

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py in get_asset(self, genome_name, asset_name, tag_name, seek_key, strict_exists, check_exist, enclosing_dir)
    311                          tag_name=tag_name, seek_key=seek_key,
    312                          strict_exists=strict_exists, check_exist=check_exist,
--> 313                          enclosing_dir=enclosing_dir)
    314 
    315     def get_default_tag(self, genome, asset, use_existing=True):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py in seek(self, genome_name, asset_name, tag_name, seek_key, strict_exists, enclosing_dir, check_exist)
    275             msg += ". These paths exist: {}".format(extant)
    276         if strict_exists is True:
--> 277             raise OSError(msg)
    278         else:
    279             warnings.warn(msg, RuntimeWarning)

OSError: For genome 'mouse_chrM2x' the asset 'bowtie2_index.None:default' doesn't exist; tried bowtie2_index/default/mouse_chrM2x and /Users/mstolarczyk/Desktop/testing/r/mouse_chrM2x/bowtie2_index/default/mouse_chrM2x

In [5]: rgc.seek("mouse_chrM2x","bowtie2_index")                                                                                                                                                          
Out[5]: '/Users/mstolarczyk/Desktop/testing/r/mouse_chrM2x/bowtie2_index/default/mouse_chrM2x'
```

**Comment by jpsmith5** [comment]
@stolarczyk  Is seek() already in the released versions? I hadn't thought that was already out there. I had updated for the change in asset naming (including or not including the reference in the path), but not the change from get_asset() to seek()...

**Comment by stolarczyk** [comment]
yes, it's released in refgenconf v0.7.0

**Comment by jpsmith5** [comment]
Ah. Okay. Updated, works with test sample, and pushing changes now.

**Comment by stolarczyk** [comment]
keep in mind that seek does not check for asset existence at all. You can opt in with `check_exist=True` if you want to check for assets other than bowtie2_index

**Comment by jpsmith5** [comment]
@wongwic Give the just released version a go. Should resolve this error.

**Comment by wongwic** [comment]
Okay, will give it a try!

**Comment by wongwic** [comment]
Hmm, the bowtie2_index error was resolved but getting a new error now:

`grep 'Reads that were too short:' /home/ww377/peppro_example/test/cutadapt/test_R1_cutadapt.txt | awk '{print $(NF-1)}'`
Traceback (most recent call last):
  File "./pipelines/peppro.py", line 3848, in <module>
    sys.exit(main())
  File "./pipelines/peppro.py", line 2227, in main
    untrimmed_fastq1, outfolder=param.outfolder)
  File "./pipelines/peppro.py", line 1335, in _process_fastq
    follow=report_fastq)
  File "/home/ww377/.local/lib/python3.6/site-packages/pypiper/manager.py", line 795, in run
    call_follow()
  File "/home/ww377/.local/lib/python3.6/site-packages/pypiper/manager.py", line 672, in call_follow
    follow()
  File "./pipelines/peppro.py", line 1128, in report_fastq
    ts = float(pm.checkprint(ts_cmd).replace(',',''))
ValueError: could not convert string to float:

**Comment by jpsmith5** [comment]
Hmm. I haven't seen that one before. I ran through the same command you originally began with successfully. Let me dive in and see if I can find out what's happening here.

**Comment by jpsmith5** [comment]
Hi @wongwic, I moved this next issue over to a fresh issue so we can track the different error more clearly. See #65
