### ISSUE TITLE
cutadapt related ValueError

### ISSUE THREAD

**Issue by jpsmith5** [databio/peppro#65]
Hmm, the bowtie2_index error was resolved but getting a new error now:

`grep 'Reads that were too short:' /home/ww377/peppro_example/test/cutadapt/test_R1_cutadapt.txt | awk '{print $(NF-1)}'`
Traceback (most recent call last):
  File "./pipelines/peppro.py", line 3848, in <module>
    sys.exit(main())
  File "./pipelines/peppro.py", line 2227, in main
    untrimmed_fastq1, outfolder=param.outfolder)
  File "./pipelines/peppro.py", line 1335, in _process_fastq
    follow=report_fastq)
  File "/home/ww377/.local/lib/python3.6/site-packages/pypiper/manager.py", line 795, in run
    call_follow()
  File "/home/ww377/.local/lib/python3.6/site-packages/pypiper/manager.py", line 672, in call_follow
    follow()
  File "./pipelines/peppro.py", line 1128, in report_fastq
    ts = float(pm.checkprint(ts_cmd).replace(',',''))
ValueError: could not convert string to float:

_Originally posted by @wongwic in https://github.com/databio/peppro/issues/62#issuecomment-603879657_

**Comment by jpsmith5** [comment]
@wongwic I have a couple questions and thoughts in follow-up:

1. Could you share a `cat` or a `head -n 15` to your `/home/ww377/peppro_example/test/cutadapt/test_R1_cutadapt.txt`
 - I'm wondering if there has been a change in a recent version of cutadapt that changes the output
 - I'm running on cutadapt version 2.3 
2. Alternatively, it's related to a different version of awk or grep potentially, and it's returning an empty string where I expect a value.
3. Are you running on Linux it looks like? Or macOS?

I have a feeling this is related to a change in cutadapt where the terminology or column spacing has updated. I'll test the newest version of cutadapt on my end to see if that's the source.

**Comment by jpsmith5** [comment]
A ha! Cutadapt v2.9 does not include a "too short" parameter in the output. Let me see if that is now a non-default option, or if they completely eliminated it as a reportable feature.

**Comment by jpsmith5** [comment]
Alright @wongwic, this should be addressed in the newest release 0.9.3.  Thanks for spotting this.

**Comment by wongwic** [comment]
Thanks, cutadapt issue has been resolved.
