### ISSUE TITLE
Index file location is wrong

### ISSUE THREAD

**Issue by wongwic** [databio/peppro#67]
Another issue: the pipeline appears to feed the wrong base name of the index. 

`bowtie2 -p 1 --very-sensitive -X 2000 --rg-id test -x /home/ww377/hg38/bowtie2_index/default/hg38/hg38 -U /home/ww377/peppro_example/test/fastq/test_R1_processed.fastq | samtools view -bS - -@ 1  | samtools sort - -@ 1 -T /home/ww377/peppro_example/test/aligned_hg38/tmpcttxsjqf -o /home/ww377/peppro_example/test/aligned_hg38/test_temp.bam` (50133,50135,50137)
<pre>
(ERR): "/home/ww377/hg38/bowtie2_index/default/hg38/hg38" does not exist or is not a Bowtie 2 index
Exiting now ...

I think it the index location should have been /home/ww377/hg38/bowtie2_index/default/hg38. Can I resolve this in the genome_config.yaml?

**Comment by jpsmith5** [comment]
I think this is related to the changes in refgenconf. There is clearly some version differences happening between us here as I again was able to run the test case through without error. I'm looking into this now.

**Comment by nsheff** [comment]
need this: If you type `refgenie seek hg38/bowtie2_index` what do you see?

**Comment by nsheff** [comment]
> Can I resolve this in the genome_config.yaml?

No, this is actually a problem in the pipeline. don't change the genome config. It's just a particular path through the pipeline that didn't get updated.

**Comment by stolarczyk** [comment]
it looks like the `seek` method worked as expected (returned path to bowtie2 directory and appended genome base). But Bowtie2 _software_ does not recognize the path with genome base appended? This error is clearly produced by Bowtie2: https://www.biostars.org/p/383285/

**Comment by jpsmith5** [comment]
It's the double reference being added. I caught a spot in the pipeline that in my testing wasn't being called but still used the old logic before refgenie changed how it generated bowtie2_index paths.  So I believe it's corrected now.

**Comment by jpsmith5** [comment]
Alright @wongwic, sorry for the difficulties. I hadn't caught a spot where recent changes in companion software required updates. Check out the current release if you would please. Thank you for your patience in resolving these issues.

**Comment by wongwic** [comment]
Thanks! Running it now, will update when it completes.

**Comment by wongwic** [comment]
The pipeline has successfully run. Thanks a lot!

**Comment by jpsmith5** [comment]
Glad to hear it! Thanks for working with us to find those new issues.
