### ISSUE TITLE
FRIF calculation issue

### ISSUE THREAD

**Issue by wongwic** [databio/peppro#69]
I was using a custom annotation file while running peppro, and got the following issue when the frif was being calculated.  Any idea what the cause of this could be? I have a pretty strange annotation file, but I think my bed file conforms to the standard listed on the site. 

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 2
Calls: plotFRiF -> calcFRiF -> cbind -> cbind -> data.frame
Execution halted
</pre>
Command completed. Elapsed time: 0:00:32. Running peak memory: 2.795GB.  
  PID: 21430;	Command: Rscript;	Return code: 1;	Memory used: 0.074GB

**Comment by jpsmith5** [comment]
Would you be able to share your custom file? Then I'll test it in my hands and see if I can spot the source of the issue.

May be an area in the function that I can improve messaging for this sort of issue in the future as well.

**Comment by jpsmith5** [comment]
I'm thinking there's a missing expected column in the coverage files, but looking at the annotation file may give me some insight.  If you'd also share the` PEPPRO_log.md` file that'd be helpful.

**Comment by wongwic** [comment]
Thanks for looking into this.

[PEPPRO_log.txt](https://github.com/databio/peppro/files/4389154/PEPPRO_log.txt)
[Capsaspora_owczarzaki_atcc_30864_gca_000151315_annotation.txt](https://github.com/databio/peppro/files/4389160/Capsaspora_owczarzaki_atcc_30864_gca_000151315_annotation.txt)

**Comment by jpsmith5** [comment]
Hey @wongwic, would you be able to also share one of the input files to the `frif` plotting function. Maybe just the smallest of the following:
```
/local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_CDS_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_biological_region_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_exon_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_five_prime_UTR_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_gene_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_lnc_RNA_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_mRNA_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_ncRNA_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_ncRNA_gene_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_rRNA_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_snRNA_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_supercontig_plus_coverage.bed  
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_tRNA_plus_coverage.bed    
 /local/storage/projects/NASA_2020/Capsaspora_r1/peppro/Capsaspora_r1/QC_Capsaspora_owczarzaki/Capsaspora_r1_three_prime_UTR_plus_coverage.bed
```

If they're all of reasonable size, you could pass along all of them if it's not too much trouble, but I'd like to at least look at one of them to see what I'm working with.

**Comment by wongwic** [comment]
[Capsaspora_bed.zip](https://github.com/databio/peppro/files/4390105/Capsaspora_bed.zip)

**Comment by jpsmith5** [comment]
Aha! Got it. A handful of the annotation regions/files/features have start positions of 0. 

| feature file                                  | zero count |
|-----------------------------------------------|------------|
| `Capsaspora_r1_ncRNA_gene_plus_coverage.bed`  | 1          |
| `Capsaspora_r1_rRNA_plus_coverage.bed`        | 1          |
| `Capsaspora_r1_supercontig_plus_coverage.bed` | 84         |
| `Capsaspora_r1_exon_plus_coverage.bed`        | 1          |

Then, the problem arises with `Capsaspora_r1_supercontig_plus_coverage.bed` as the file is only 84 regions in total.  This creates an issue where I had checked for 0's in rows, not expecting the start position to ever be zero.  This is insignificant in the other files as it's only one row, but it's the entire file for the `supercontig`, thus creating an empty file.  

I'm modifying on my side to handle this and will update again when I've released the new version. Thanks so much for working with me here.

**Comment by jpsmith5** [comment]
Alright @wongwic. Check out the most recent release. Should address the issue you came across.

I was able to use your files to produce the following plots after the changes.
![frif](https://user-images.githubusercontent.com/29147871/77712177-761d2880-6fa9-11ea-811a-790f4b8e62d5.png)
![cfrif](https://user-images.githubusercontent.com/29147871/77712178-761d2880-6fa9-11ea-9ba7-2531dbfed37e.png)

**Comment by wongwic** [comment]
Went well on my end. Thanks.
