### ISSUE TITLE
Error: missing fasta file 

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#7]
```
Failure reason: Could not find hg38.fa in /project/shefflab/genomes/hg38/bowtie2_index.

Changed status from running to failed.
Traceback (most recent call last):
  File "pipelines/peppro.py", line 3012, in <module>
    sys.exit(main())
  File "pipelines/peppro.py", line 1595, in main
    _check_bowtie2_index(res.rgc, args.genome_assembly)
  File "pipelines/peppro.py", line 1266, in _check_bowtie2_index
    err_msg.format(genome_assembly, bt2_path)))
  File "/usr/local/lib/python3.6/dist-packages/pypiper/manager.py", line 1639, in fail_pipeline
    raise e
OSError: Could not find hg38.fa in /project/shefflab/genomes/hg38/bowtie2_index.
```

Why are we testing if a fasta file is in the bowtie2 index folder?

**Comment by jpsmith5** [comment]
In our primary genomes folder location on /nm/ it always included a symlink in the indexed_bowtie2 folder by default, so I had always been checking for that to ensure the index was complete.  But if that's not automatically included anymore we can drop our the check.

**Comment by nsheff** [comment]
If we don't need the fasta file, why would we check for it? Let's take it out completely, then, if it's not used.

Right now there are almost 100 lines of code dedicated to making sure the bowtie2 indexes are complete. I think we need to just offload this task to refgenie or something else. if the `get_asset` call works, then we're good to go.

along these lines,:

https://github.com/databio/peppro/blob/87e78f5c969609dca2c274e0ba3dc11841544ae7/pipelines/peppro.py#L1232-L1234

are you sure these are exactly what bowtie2 needs for all genomes? I figured it was related to the size of the reference. why do we need to check for every single index file? is it common to have some partially-completed indexes (I've never run into anything related to this)

also, are we using both bowtie2 small and large indexes? how is that relevant?

**Comment by jpsmith5** [comment]
Small and large depends on the genome. My understanding was that yes those files are constant in naming convention and number, which is why I always checked for each component. This is still a carry-over of pre refgenie, but if refgenie has subsumed those responsibilities then yes we can just cut this whole function.

**Comment by jpsmith5** [comment]
Moved to just `refgenie` checks with `_add_resources` function.  Removed `check_bowtie2_index`.
