### ISSUE TITLE
SyntaxError in test project

### ISSUE THREAD

**Issue by stolarczyk** [databio/peppro#75]
@jpsmith5, #73 is fixed. Now I'm getting a SyntaxError

[log](https://github.com/databio/peppro/files/4415260/PEPPRO_log.txt)

**Comment by jpsmith5** [comment]
Hmm. This is one I’ve never seen. What version of pararead do you have?

**Comment by stolarczyk** [comment]
0.5.0

so, this dependency is not containerized. peppro uses host cmd?

**Comment by stolarczyk** [comment]
just upgraded to 0.7.0 and reran

**Comment by jpsmith5** [comment]
Yep. Pararead is the requirements.txt. So yes, host side. Did it run successfully or still testing?

**Comment by stolarczyk** [comment]
still running

**Comment by stolarczyk** [comment]
ok, succeeded after updating. So, I guess setting a minimal pararead version in the requirements would be a good move :)
