### ISSUE TITLE
Install/run Notes

### ISSUE THREAD

**Issue by gmnelson** [databio/peppro#79]
I've just installed PEPPRO and was able to run your example project (peppro_test.yaml) as well as my own project on our slurm cluster -- all worked great.

I followed the instructions on [peppro.databio.org](http://peppro.databio.org/en/latest/install/) to install and run, and just had a handful of minor cases where I needed to modify code or install an extra dependency. I figured I'd share those instances in case any of them can help you or other users:

- **peppro/requirements.txt**: needed to change 'loopercli' to 'looper'
- R-package **GenomicDistributionsData**: required the dependency packages 'BSgenome', 'GenomicFeatures', and 'ensembldb'
- **peppro/examples/meta/peppro_test.yaml**: $PROCESSED and $CODE undefined -- just replaced with absolute paths to run the demo
- **peppro/docs/install.md**: to run the demo, I also had to refgenie pull the hg38 'fasta' asset
- **peppro/docs/cluster.md**: -c flag not necessary nor allowed in 'divvy init config'
- **peppro/docs/tutorial.md**: 'looper summarize' does not appear to exist -- changed to 'looper report' to get HTML report

**Comment by jpsmith5** [comment]
Hey @gmnelson, thanks so much for this. It’s always helpful getting this sort of feedback. We’re constantly pushing our companion software forward and looks like you caught some spots needing catching up. Thanks for identifying and sharing and I’ll be sure to update where needed.
