### ISSUE TITLE
required checks

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#8]
right now we're checking for lots of stuff in required that I thought was optional; for instance I thought you said `seqOutBias` was optional, but it's listed as required here:

```
The following required tool(s) are not callable: seqkit fastp cutadapt seqtk fastq_pair seqOutBias
```

Also not listed as required in the docs: http://peppro.databio.org/en/latest/install/

**Comment by jpsmith5** [comment]
It's not required and I thought it was working correctly.  I must not have tested it again on a system without seqOutBias installed to confirm.  Will correct that section.

**Comment by nsheff** [comment]
ok, those other ones are all required though?

**Comment by jpsmith5** [comment]
yes they are
