### ISSUE TITLE
Custom Adapters

### ISSUE THREAD

**Issue by CriticalSci** [databio/peppro#80]
Hi there,

How does one apply an adapter set other than the default?

I've tried:
- adding an entry in the looper input .yaml
- modifying the `pipelines/peppro.yaml`
- replacing with my own sequences in `tools/adapter.fa`

Many thanks!

**Comment by nsheff** [comment]
it should be done by modifying this line:

https://github.com/databio/peppro/blob/37196bf805d7d62a8acdd0fa60c0bcdfacf15ed0/pipelines/peppro.yaml#L27

If you've tried that and it didn't work, then that's a bug in peppro. @jpsmith5 ?

**Comment by jpsmith5** [comment]
Hey @CriticalSci, yes that is how you would do it, and it did identify a bug. I found an incorrect order of argument terms that was disrupting this.  Just pushed the changes and making a new release now.  Try pulling the most recent changes or grabbing the new release and give it another go.

**Comment by CriticalSci** [comment]
Great, thanks for implementing the fix so quickly!

I pulled the recent changes and the custom adapters are being loaded correctly into the pipeline now according to the log :)

Many thanks!
