### ISSUE TITLE
some wrong with cutadapt

### ISSUE THREAD

**Issue by NJU-Bio-Info** [databio/peppro#81]

**Comment by jpsmith5** [comment]
Hey @NJU-Bio-Info, did you resolve the error you saw with cutadapt? Was it a version difference? Happy to look into it if you were still experiencing the issue.

**Comment by NJU-Bio-Info** [comment]
Hi, fine to receive your letter and I'd like to tell you I have solved this problem. But there is another question that why I can not get any&nbsp;png file when I try to run peppro directly in your manual with your test data? Should I must run some other steps to get png files or a html report?
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Jason ***@***.***&gt;;
Date: &nbsp;Wed, Nov 3, 2021 08:04 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [databio/peppro] some wrong with cutadapt (Issue #81)

&nbsp;



 
Hey @NJU-Bio-Info, did you resolve the error you saw with cutadapt? Was it a version difference? Happy to look into it if you were still experiencing the issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
