### ISSUE TITLE
Unable to download the tutorial fastq files

### ISSUE THREAD

**Issue by anaga2** [databio/peppro#85]
The following links to download the tutorial datasets are broken.
wget http://big.databio.org/peppro/fastq/tutorial_r1.fq.gz
wget http://big.databio.org/peppro/fastq/tutorial_r2.fq.gz

**Comment by nsheff** [comment]
Our server is down at the moment, but we're working on it.

**Comment by jpsmith5** [comment]
Hey @anaga2 Sorry about that, server had been down for a moment. Looks like it's back up now.

**Comment by anaga2** [comment]
Thank you for the prompt response! I could download the files.
