### ISSUE TITLE
Issues and fixes for a conda-based installation used to run peppro_test example.

### ISSUE THREAD

**Issue by todddeluca** [databio/peppro#87]
First let me say thank you for the excellent installation notes at http://peppro.databio.org/en/latest/install/. I'm dropping this in here because the installation process was quite involved and a number of issues cropped up that needed to be discovered and solved. Hopefully this can be useful to the developer or other users troubleshooting installation. Some issues had to do with versioning in conda. Some had to do with steps not mentioned in the installation notes. Or things that did not work in the installation notes. The following is what I did to successfully run the `peppro_test` example included in the github repo.

Create conda env for PEPPRO:
```
conda create -y -n peppro python=3.9
conda activate peppro
conda config --env --add channels conda-forge
conda config --env --add channels bioconda
```

Installation fails spectacularly with strict channel priority. Too many conflicting version requirements.
```
conda config --env --set channel_priority false
```

PEPPRO requires R:
```
conda install -c conda-forge r-base=4.1 r-essentials=4.1
```

PEPPRO requires bedtools ucsc-bigwigcat bowtie2 fastq-pair flash picard preseq seqkit samtools seqtk ucsc-wigtobigwig
**Issue**: R devtools requires usethis which requires gert which fails to install via R. Use conda instead to install r-gert from conda-forge
**Issue**: the peppro test example requires fastp.
```
conda install -y fastqc r-gert bedtools ucsc-bigwigcat bowtie2 fastq-pair flash picard preseq seqkit samtools seqtk ucsc-wigtobigwig fastp 
```

**Issue**: update samtools to fix a "missing libcrypto.so.1.0.0" bug. upgrades from 1.7.1 to 1.14
```
conda update samtools
```

**Issue**: update ucsc bigwig tools to fix "missing libssl.so.1.0.0" bug. upgrades from version 357 to 377.
```
conda update ucsc-wigtobigwig ucsc-bigwigcat
```

Install peppro
```
cd ~/ph # my project directory
git clone https://github.com/databio/peppro.git
cd peppro
```

Install python packages
```
pip install --user -r requirements.txt
```

Install r packages.
**Issue**: If you don't already have a CRAN mirror specified in ~/.Rprofile, add this line (using whatever mirror works best for you):
```
options(repos=structure(c(CRAN="http://cran.us.r-project.org")))                                                                                                                                            
```

Install R packages. This took a long time:
```
which Rscript # should point to your conda env R.
Rscript -e 'install.packages("devtools")'
Rscript -e 'devtools::install_github("pepkit/pepr")'
Rscript -e 'install.packages("BiocManager")'
Rscript -e 'BiocManager::install("GenomicRanges")'
Rscript -e 'devtools::install_github("databio/GenomicDistributions")'
Rscript -e 'BiocManager::install(c("BSgenome", "GenomicFeatures", "ensembldb"))' # wow this took FOREVER
Rscript -e 'install.packages("http://big.databio.org/GenomicDistributionsData/GenomicDistributionsData_0.0.1.tar.gz", repos=NULL)'
Rscript -e 'devtools::install(file.path("PEPPROr/"), dependencies=TRUE, repos="https://cloud.r-project.org/")'
```

Initialize refgenie
```
export REFGENIE=~/ph/data/refgenie/genome_config.yaml
# optional: add REFGENIE to ~/.bashrc (or your preferred config file)
refgenie init -c $REFGENIE
refgenie pull -g hg38 -a fasta bowtie2_index ensembl_gtf ensembl_rb refgene_anno
```

**Issue**: feat_annotation could not be pulled. Build it as a "derived asset".
```
# see http://refgenie.databio.org/en/latest/available_assets/
refgenie build hg38/feat_annotation
```
Pull remaining assets:
```
refgenie pull -g human_rDNA -a bowtie2_index
```

Test peppro using an example. **Issue**: $CODE and $PROCESSED env vars need to be defined (as absolute paths?). Fix: define them in the looper command line.
```
cd ~/ph
# Dry run:
CODE=~/ph PROCESSED=~/ph/data/peppro_test looper run -d peppro/examples/meta/peppro_test.yaml
# Real run:
# rm -rf data/peppro_test/peppro # clean up old results before rerunning
CODE=~/ph PROCESSED=~/ph/data/peppro_test looper run peppro/examples/meta/peppro_test.yaml
```

**Comment by jpsmith5** [comment]
Hi @todddeluca, I've added a conda environment file and a [guide to the docs to run with conda](https://peppro.databio.org/en/latest/run-conda/). If you want to give that a go and confirm it's good in your hands it's in the main branch now ready to go. Feel free to reopen if you hit any issues, but this was working successfully in my hands.
