### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by teresho4** [databio/peppro#88]
Dear databio team,

Can you please update the docker image?  It was not updated for 2 years and I failed to run the pipeline because of several errors you already solved in new package versions.

Thank you!

**Comment by jpsmith5** [comment]
Hey @teresho4, while we encourage people to [try using `bulker` to work with containers](https://bulker.databio.org/en/latest/peppro/), I know some people like the single Dockerfile style approach. There's a [new version on Docker hub](https://hub.docker.com/r/databio/peppro) and a Dockerfile in the repository now. If you hit an issue with that version feel free to reopen this issue.

**Comment by teresho4** [comment]
Dear @jpsmith5, 

Unfortunately, it is impossible to use bulker on the RIS server, so I am limited to that issue and can use only Docker.

**Comment by nsheff** [comment]
Thanks @teresho4 -- but what is RIS, and why specifically can't you use bulker?

**Comment by teresho4** [comment]
Dear @nsheff,
RIS is research infrastructure service, that provides computing resources, such as cluster/server for university workers. 
While using the cluster/server I can use only docker images for my work.

Thank you.

**Comment by nsheff** [comment]
Hii @teresho4 -- bulker is just a Python package that uses docker. If you can use docker, then you probably shouldn't have any trouble using bulker.

**Comment by teresho4** [comment]
Ok, now I see that you have updated the Docker image for peppro. Sorry, I missed that.
I will try to use it directly without using bulker.

Thank you!

**Comment by nsheff** [comment]
?

**Comment by teresho4** [comment]
I can't install any python packages on the server, I can use them only within any docker container. That is why I will try to use the peppro docker directly without bulker.
