### ISSUE TITLE
prealignment with mouse rDNA

### ISSUE THREAD

**Issue by dahun73** [databio/peppro#97]
Hello :)

I'm trying to set up peppro for mouse genome. I found that there is no mouse rDNA fasta and chrom.sizes files in refgenie database. I downloaded other references(gtf, fasta, bowtie2 index and so on). So,  I should make mouse rDNA reference files manually. 

In this situation, I have some questions.

1) How do I download mouse rDNA(rRNA) sequences and rDNA chromsize file?
I downloaded from UCSC genome browser for rmsk. But, it is quite different format comparing with human_rDNA in refgenie(For refgenie, there is one header in fasta. In my case, however, there are many headers in fasta file). And, I could not find  mouse rDNA chromsizes file yet...

2) Is there any defined format for making index? If it is, could you let me know file format briefly?
The reason why I ask about this question is that I downloaded other reference files using refgenie. I have concern about crash between downloaded other reference files and custom mouse rDNA reference.

Thank you in advance :)

Dahun

**Comment by jpsmith5** [comment]
Hey @dahun73,

I tracked down a mouse complete ribosomal repeating sequence that I believe should work for you here and generated both the [`fasta` and `bowtie2_index` assets](http://big.databio.org/peppro/genomes/mouse/mm_rDNA/).  I'll work to add this to the `refgenie` servers so it's available directly via the `refgenie` interface, but this should work in the short term.  You can also download just that `fasta` sequence and add it to your existing `refgenie` genomes like so:

```
refgenie build mm_rDNA/fasta --files fasta=mm_rDNA.fa.gz --genome-description Mouse ribosomal DNA, complete repeating unit

refgenie build mm_rDNA/bowtie2_index 
```

Building the `fasta` asset with `refgenie` will automatically generate that chromosome sizes file, and I put it in that folder I linked to above as a backup.

And which index are you asking about here? Do you mean regarding constructing the bowtie2 index for the ribosomal sequence?

**Comment by dahun73** [comment]
Dear @jpsmith5,

Thank you for kind answer!

> And which index are you asking about here? Do you mean regarding constructing the bowtie2 index for the ribosomal sequence?

Yes! I wonder there is a defined format about rDNA bowtie2 index because there is a format of mm10 bowtie2 index like this;
![image](https://user-images.githubusercontent.com/52641420/206964592-dd49e885-ec7a-4da8-8315-644318c9834c.png)
So, I asked I should make directories following this format.

As your suggestion, I tried to build using rDNA sequence. I want to check again if this sequence is right.
https://www.ncbi.nlm.nih.gov/nuccore/BK000964.3?report=fasta
I think format is different from UCSC genome browser and from NCBI.
For NCBI, there is one header of rDNA. However, in UCSC genome browser, there are many headers(I think it is split by type of rDNA).

**Comment by jpsmith5** [comment]
Hi @dahun73,

Yeah, so there is flexibility here. Really any input `fasta` file is acceptable, whether it is a single or multi header file, and yes that is the source file in this case.  You should be fine using a different ribosomal sequence, even if its split between 18s et cetera headers.  The actual index is generated using `bowtie2-build` which simply requires the input `fasta` sequence, the same as if you were manually constructing a new index for any genome of interest. If you were to `ls` that `bowtie2_index` subfolder, you'll see the typical file structure of any `bowtie2_index` as constructed by `bowtie2-build`.

You can use the `-q` flag with `refgenie build` to see a build recipe's requirements. e.g.
```
refgenie build mm_rDNA/bowtie2_index -q
'bowtie2_index' recipe requirements:
- assets:
        fasta (fasta asset for genome); default: fasta
```
In this case, if you already have the `fasta` asset managed by `refgenie`, you don't even need to point to it, `refgenie` will automatically use the prebuilt `fasta` asset.  See also: http://refgenie.databio.org/en/latest/build/#what-assets-can-refgenie-build

You can also [look at the recipes under the hood of `refgenie` here.](https://github.com/refgenie/recipes)

**Comment by dahun73** [comment]
> Hi @dahun73,
> 
> Yeah, so there is flexibility here. Really any input `fasta` file is acceptable, whether it is a single or multi header file, and yes that is the source file in this case. You should be fine using a different ribosomal sequence, even if its split between 18s et cetera headers. The actual index is generated using `bowtie2-build` which simply requires the input `fasta` sequence, the same as if you were manually constructing a new index for any genome of interest. If you were to `ls` that `bowtie2_index` subfolder, you'll see the typical file structure of any `bowtie2_index` as constructed by `bowtie2-build`.
> 
> You can use the `-q` flag with `refgenie build` to see a build recipe's requirements. e.g.
> 
> ```
> refgenie build mm_rDNA/bowtie2_index -q
> 'bowtie2_index' recipe requirements:
> - assets:
>         fasta (fasta asset for genome); default: fasta
> ```
> 
> In this case, if you already have the `fasta` asset managed by `refgenie`, you don't even need to point to it, `refgenie` will automatically use the prebuilt `fasta` asset. See also: http://refgenie.databio.org/en/latest/build/#what-assets-can-refgenie-build
> 
> You can also [look at the recipes under the hood of `refgenie` here.](https://github.com/refgenie/recipes)

Dear @jpsmith5,

Thank you so much! I will try right now.
